### ISSUE TITLE
Silicom PXG2BPI

### ISSUE THREAD

**Issue by fjmoscatel** [russor/freebsd_bp_ctl#1]
Hello.

I'm trying to enable the Silicom PXG2BPI network card that it is recognized as intel and I can use it in opnsense.

Before doing anything, the card appeared like this in opnsense, but it did not load the modules to be able to use it.
![image](https://github.com/russor/freebsd_bp_ctl/assets/124363253/65000f28-6cd5-4805-9f2b-155786bac365)

I installed the card in its original PC, now I could use ethtool and change the vendor id and device id to Intel. I have used device 0x108A, because my device indicates that it is Intel 82546GB, should I use device 0x105E like you?

Now the card is recognized as Intel and opnsense loads the e1000 module but the card does not work, it does not obtain DHCP, and with a fixed IP it does not work either.
![image](https://github.com/russor/freebsd_bp_ctl/assets/124363253/fe9c6fcc-7b61-4983-b619-3665978adeca)

Now em0 and em1 is enabled
![image](https://github.com/russor/freebsd_bp_ctl/assets/124363253/44d6d12c-a9b0-41a0-a11c-5df7f837aa67)

What I can do?
Have I skipped any steps? do I have to install something?

I don't want to use the bypass

Thanks

**Comment by russor** [comment]
> Hello.
> 
> I'm trying to enable the Silicom PXG2BPI network card that it is recognized as intel and I can use it in opnsense.
> 
> Before doing anything, the card appeared like this in opnsense, but it did not load the modules to be able to use it. ![image](https://private-user-images.githubusercontent.com/124363253/308490132-65000f28-6cd5-4805-9f2b-155786bac365.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxNDI5NzAsIm5iZiI6MTcwOTE0MjY3MCwicGF0aCI6Ii8xMjQzNjMyNTMvMzA4NDkwMTMyLTY1MDAwZjI4LTZjZDUtNDgwNS05ZjJiLTE1NTc4NmJhYzM2NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyOFQxNzUxMTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZTk1NTNhNzgwODkyOTg1MThlZDE1ZjAyMjkyYzBjOWRlODE2NmQ1MDMwNTgxMmRhYTU5ZjYzOTM1OWNiZjE4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.alLwi0V6dwBmqlM-VrBndww4wBITvgMB7PoejF1Ahf8)
> 
> I installed the card in its original PC, now I could use ethtool and change the vendor id and device id to Intel. I have used device 0x108A, because my device indicates that it is Intel 82546GB, should I use device 0x105E like you?
> 

Looks like you have a 0x1374 / 0x0029 device; The driver calls that a PXGBPIG https://github.com/russor/freebsd_bp_ctl/blob/main/driver/bp_mod.h#L58  This looks like an older PCI-X card, not a PCI-Express card, right?

I think you really want device id 0x8086 / 0x1079, so it detects as a PXG2BPIG-SD https://github.com/russor/freebsd_bp_ctl/blob/0d260c08ae1296b918b5d79f386a24cf78b414fb/driver/bp_mod.c#L7104C1-L7104C79

> Now the card is recognized as Intel and opnsense loads the e1000 module but the card does not work, it does not obtain DHCP, and with a fixed IP it does not work either. 
>
> What I can do? Have I skipped any steps? do I have to install something?
> 
> I don't want to use the bypass
> 
> Thanks

Most likely, the card came up in bypass mode by default; and this is why you see no carrier in ifconfig (and probably no link light on your other device, if you've only installed one cable ... or a bypass condition if you installed both cables). You'll need to get bp_mod loaded and attached to your device, and run something like this:

```bpctl_util em0 set_bypass off
bcptl_util em0 set_dis_bypass on
bpctl_util em0 set_std_nic on
bpctl_util em0 set_bypass_pwoff off
bpctl_util em0 set_bypass_pwup off
bcptl_util em0 set_bypass_wd disabled
```
You probably don't exactly need all of those commands, but in case dis_bypass or set_std_nic don't work, the others should cover it. After you've run this once, the NIC will behave like a standard Intel 82546GB.

I took a quick look at the e1000 kernel source (from FreeBSD 13.2), and I don't see anything majorly different in behavior between the ID you chose and what I'd call the preferred ID. So you've got two options --- change the ID to the preferred ID, and then compile/load this module as-is; or leave the ID as-is and update the device lines in this module, and then compile and load it. Up to you --- personally, I'd switch the ID, because it'll be easier to use bypass later if you ever want to.

**Comment by fjmoscatel** [comment]
I have modified the device id to 0x1079, I have loaded the bp_mod module and I have executed the commands that you indicate with the following results:

![image](https://github.com/russor/freebsd_bp_ctl/assets/124363253/bde86fd8-06e4-4874-9375-c95ce04b8d14)

Now em0 is enabled and em0 has obtained ip by dhcp
![image](https://github.com/russor/freebsd_bp_ctl/assets/124363253/b08d0695-73be-48d8-967c-5107ec8b8526)

I have also executed the same commands for em1:
bpctl_util em1 set_dis_bypass on
bpctl_util em1 set_std_nic on
bpctl_util em1 set_bypass_pwoff off
bpctl_util em1 set_bypass_pwup off
bpctl_util em1 set_bypass_wd disabled

Both interfaces obtain IP but if I ping from the PC to em0 or em1 it does not work, I cannot connect by ssh through em0 or em1 either, both work without problem on the re0 interface. I attached default routes, in case this could be the cause.
![image](https://github.com/russor/freebsd_bp_ctl/assets/124363253/ca5519bb-2118-4281-820b-ff27e0b6bef6)

**Comment by fjmoscatel** [comment]
I have modified the device id to 0x1079, I have loaded the bp_mod module and I have executed the commands that you indicate with the following results:

![image](https://github.com/russor/freebsd_bp_ctl/assets/124363253/bde86fd8-06e4-4874-9375-c95ce04b8d14)

Now em0 is enabled and em0 has obtained ip by dhcp
![image](https://github.com/russor/freebsd_bp_ctl/assets/124363253/b08d0695-73be-48d8-967c-5107ec8b8526)

I have also executed the same commands for em1:
bpctl_util em1 set_dis_bypass on
bpctl_util em1 set_std_nic on
bpctl_util em1 set_bypass_pwoff off
bpctl_util em1 set_bypass_pwup off
bpctl_util em1 set_bypass_wd disabled

Both interfaces obtain IP but if I ping from the PC to em0 or em1 it does not work, I cannot connect by ssh through em0 or em1 either, both work without problem on the re0 interface. I attached default routes, in case this could be the cause.
![image](https://github.com/russor/freebsd_bp_ctl/assets/124363253/ca5519bb-2118-4281-820b-ff27e0b6bef6)

**Comment by russor** [comment]
Ok, so it looks like you've got the ethernet side of things going. autonegotiation and dhcp are successful.

But it looks like you've got all three interfaces on the same network, same subnet. That's not impossible to get working, but it's a challenge. Out of the box, FreeBSD is going to want to send all packets to 192.168.0.0/24 out via re0, and that might not be very helpful (especially if OPNsense has some sort of automatic firewall that drops these packets?). You might look into lagg to use multiple NICs at once on a single network, but it works best when the other side of the link can also do aggregation, which usually means a managed switch.

If you want to confirm your silicom nic works, you might want to set opnsense to use em0 as the LAN port, and only connect one cable (you'll have to figure out which port is em0 and which is em1; it will be consistent once you figure it out), and confirm everything works. Then set it for em1 as LAN and swap the cable.

Assuming the NICs all work individually, getting them to work how you want them to is kind of out of scope of my repo here. :)

**Comment by fjmoscatel** [comment]
> Looks like you have a 0x1374 / 0x0029 device; The driver calls that a PXGBPIG https://github.com/russor/freebsd_bp_ctl/blob/main/driver/bp_mod.h#L58 This looks like an older PCI-X card, not a PCI-Express card, right?

Yes, the card is PCI-X, it is older

> But it looks like you've got all three interfaces on the same network, same subnet. That's not impossible to get working, but it's a challenge. Out of the box, FreeBSD is going to want to send all packets to 192.168.0.0/24 out via re0, and that might not be very helpful (especially if OPNsense has some sort of automatic firewall that drops these packets?). You might look into lagg to use multiple NICs at once on a single network, but it works best when the other side of the link can also do aggregation, which usually means a managed switch.

Now, I only have a single network in my house.
The card works, I have verified that it works well in Debian and the two Ethernet ports work correctly.

I'm new to freebsd and opnsense, I just installed it. Now I will create different VLANs and I will configure the cards on different networks.

Thank you very much for your help, you are fantastic.
